#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Display Setup
xrandr --output HDMI-A-0 --mode "1920x1080" &

sxhkd &

killall dunst
dunst &

nitrogen --restore &

picom --experimental-backends --config ~/.config/picom/picom.conf &

flameshot &

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar top --quiet &

xset -dpms s off

bspc config border_width          1
bspc config window_gap            8

bspc config normal_border_color   \#32344a
bspc config focused_border_color  \#444b6a

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Ristretto state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a nitrogen state=floating center=true
bspc rule -a Screenkey manage=off
